#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=1
#PBS -l walltime=1:00:00
#PBS -N log_check_iq
#PBS -o $PBS_JOBNAME.out
#PBS -e $PBS_JOBNAME.err
#PBS -A hpc_phyleaux11


WDIR=$PBS_O_WORKDIR
cd $WDIR


echo 'scleroglossa.constraint'
ls */*.scleroglossa.constraint.iqtree | wc -l

echo 'toxicoferaP.constraint'
ls */*.toxicoferaP.constraint.iqtree | wc -l

echo 'toxicoferaAI.constraint'
ls */*.toxicoferaAI.constraint.iqtree | wc -l

echo 'toxicoferaSA.constraint'
ls */*.toxicoferaSA.constraint.iqtree | wc -l

echo 'toxicoferaSI.constraint'
ls */*.toxicoferaSI.constraint.iqtree | wc -l