#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=1
#PBS -l walltime=20:00:00
#PBS -N log_zipIQ_Streicher
#PBS -o $PBS_JOBNAME.out
#PBS -e $PBS_JOBNAME.err
#PBS -A hpc_phyleaux11


WDIR=$PBS_O_WORKDIR
cd $WDIR


dataSet='Streicher'


# rename datasets
mv $dataSet'IQ/MaxLikeSummaryNA.txt' $dataSet'IQ'/$dataSet'MaxLikeSummaryNA.txt'
mv $dataSet'IQ/MaxLikeSummary.txt' $dataSet'IQ'/$dataSet'MaxLikeSummary.txt'

# make dir to store all the scripts and output for easy download later
mkdir $dataSet'IQ/ScriptsLogsOutput'$dataSet
cp $dataSet'IQ/'*.{pbs,sh,py,log,out,err,txt} $dataSet'IQ/ScriptsLogsOutput'$dataSet

# Zip
zip -r $dataSet'IQlogs.zip' $dataSet'IQ'/*/*.{log,iqtree}
zip -r $dataSet'IQ.zip' $dataSet'IQ'/
