#!/bin/bash

grep "Agama_agama" tacocat_allconstraint.bb | wc -l
grep "Anolis_carolinensis" tacocat_allconstraint.bb | wc -l
grep "Basiliscus_basiliscus" tacocat_allconstraint.bb | wc -l
grep "Brachylophus_fasciatus" tacocat_allconstraint.bb | wc -l
grep "Brookesia_brygooi" tacocat_allconstraint.bb | wc -l
grep "Calotes_emma" tacocat_allconstraint.bb | wc -l
grep "Chalarodon_madagascariensis" tacocat_allconstraint.bb | wc -l
grep "Chamaeleo" tacocat_allconstraint.bb | wc -l
grep "Corytophanes_cristatus" tacocat_allconstraint.bb | wc -l
grep "Crotaphytus_collaris" tacocat_allconstraint.bb | wc -l
grep "Dipsosaurus_dorsalis" tacocat_allconstraint.bb | wc -l
grep "Enyalioides_laticeps" tacocat_allconstraint.bb | wc -l
grep "Gambelia_wislizenii" tacocat_allconstraint.bb | wc -l
grep "Hydrosaurus" tacocat_allconstraint.bb | wc -l
grep "Leiocephalus_barahonensis" tacocat_allconstraint.bb | wc -l
grep "Leiolepis_belliana" tacocat_allconstraint.bb | wc -l
grep "Leiosaurus_catamarcensis" tacocat_allconstraint.bb | wc -l
grep "Liolaemus_bellii" tacocat_allconstraint.bb | wc -l
grep "Morunasaurus_annularis" tacocat_allconstraint.bb | wc -l
grep "Oplurus_cyclurus" tacocat_allconstraint.bb | wc -l
grep "Petrosaurus_mearnsi" tacocat_allconstraint.bb | wc -l
grep "Phrynosoma_platyrhinos" tacocat_allconstraint.bb | wc -l
grep "Phymaturus_palluma" tacocat_allconstraint.bb | wc -l
grep "Physignathus_cocincinus" tacocat_allconstraint.bb | wc -l
grep "Plica_plica" tacocat_allconstraint.bb | wc -l
grep "Pogona_vitticeps" tacocat_allconstraint.bb | wc -l
grep "Polychrus_marmoratus" tacocat_allconstraint.bb | wc -l
grep "Pristidactylus_torquatus" tacocat_allconstraint.bb | wc -l
grep "Sauromalus_ater" tacocat_allconstraint.bb | wc -l
grep "Sceloporus_variabilis" tacocat_allconstraint.bb | wc -l
grep "Stenocercus_guentheri" tacocat_allconstraint.bb | wc -l
grep "Uma_scoparia" tacocat_allconstraint.bb | wc -l
grep "Uranoscodon_superciliosus" tacocat_allconstraint.bb | wc -l
grep "Uromastyx_aegyptus" tacocat_allconstraint.bb | wc -l
grep "Urostrophus_vautieri" tacocat_allconstraint.bb | wc -l
grep "Uta_stansburiana" tacocat_allconstraint.bb | wc -l
