#!/bin/bash


grep "Agama_agama" tacocat_allconstraint.bb | cut -c 1-20
grep "Anolis_carolinensis" tacocat_allconstraint.bb | cut -c 1-20
grep "Basiliscus_basiliscus" tacocat_allconstraint.bb | cut -c 1-20
grep "Brachylophus_fasciatus" tacocat_allconstraint.bb | cut -c 1-20
grep "Brookesia_brygooi" tacocat_allconstraint.bb | cut -c 1-20
grep "Calotes_emma" tacocat_allconstraint.bb | cut -c 1-20
grep "Chalarodon_madagascariensis" tacocat_allconstraint.bb | cut -c 1-20
grep "Chamaeleo" tacocat_allconstraint.bb | cut -c 1-20
grep "Corytophanes_cristatus" tacocat_allconstraint.bb | cut -c 1-20
grep "Crotaphytus_collaris" tacocat_allconstraint.bb | cut -c 1-20
grep "Dipsosaurus_dorsalis" tacocat_allconstraint.bb | cut -c 1-20
grep "Enyalioides_laticeps" tacocat_allconstraint.bb | cut -c 1-20
grep "Gambelia_wislizenii" tacocat_allconstraint.bb | cut -c 1-20
grep "Hydrosaurus" tacocat_allconstraint.bb | cut -c 1-20
grep "Leiocephalus_barahonensis" tacocat_allconstraint.bb | cut -c 1-20
grep "Leiolepis_belliana" tacocat_allconstraint.bb | cut -c 1-20
grep "Leiosaurus_catamarcensis" tacocat_allconstraint.bb | cut -c 1-20
grep "Liolaemus_bellii" tacocat_allconstraint.bb | cut -c 1-20
grep "Morunasaurus_annularis" tacocat_allconstraint.bb | cut -c 1-20
grep "Oplurus_cyclurus" tacocat_allconstraint.bb | cut -c 1-20
grep "Petrosaurus_mearnsi" tacocat_allconstraint.bb | cut -c 1-20
grep "Phrynosoma_platyrhinos" tacocat_allconstraint.bb | cut -c 1-20
grep "Phymaturus_palluma" tacocat_allconstraint.bb | cut -c 1-20
grep "Physignathus_cocincinus" tacocat_allconstraint.bb | cut -c 1-20
grep "Plica_plica" tacocat_allconstraint.bb | cut -c 1-20
grep "Pogona_vitticeps" tacocat_allconstraint.bb | cut -c 1-20
grep "Polychrus_marmoratus" tacocat_allconstraint.bb | cut -c 1-20
grep "Pristidactylus_torquatus" tacocat_allconstraint.bb | cut -c 1-20
grep "Sauromalus_ater" tacocat_allconstraint.bb | cut -c 1-20
grep "Sceloporus_variabilis" tacocat_allconstraint.bb | cut -c 1-20
grep "Stenocercus_guentheri" tacocat_allconstraint.bb | cut -c 1-20
grep "Uma_scoparia" tacocat_allconstraint.bb | cut -c 1-20
grep "Uranoscodon_superciliosus" tacocat_allconstraint.bb | cut -c 1-20
grep "Uromastyx_aegyptus" tacocat_allconstraint.bb | cut -c 1-20
grep "Urostrophus_vautieri" tacocat_allconstraint.bb | cut -c 1-20
grep "Uta_stansburiana" tacocat_allconstraint.bb | cut -c 1-20
