#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=8
#PBS -l walltime=24:00:00
#PBS -N log_singhalOG_HoT
#PBS -o $PBS_JOBNAME.out
#PBS -e $PBS_JOBNAME.err
#PBS -A hpc_phyleaux11

dataset='SinghalOG'
input='gene.list'

cd $PBS_O_WORKDIR


# Move files make sure to check paths in python script 
python3 MoveNexToFasta.py $dataset

# Make list of fasta files 
rm $input
for x in *.fasta; do echo $x >> $input; done

JOBS_PER_NODE=8
TASK=$PBS_O_WORKDIR"/RunHoT.sh"
FILES=$PBS_O_WORKDIR"/"$input

# Set up parallel call
# set log file, pass workers, whatever nodefile is, and working directory
PARALLEL="parallel -j $JOBS_PER_NODE --slf $PBS_NODEFILE --wd $PBS_O_WORKDIR"

# Now call parallel and pass files and task.
$PARALLEL -a $FILES sh $TASK {} 

./GrabHoT.sh $dataset