#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:10:00
#PBS -N log_checkIQ
#PBS -o $PBS_JOBNAME.out
#PBS -e $PBS_JOBNAME.err
#PBS -A loni_lbrn_bbc_3


WDIR=$PBS_O_WORKDIR
cd $WDIR

rm ERRORS.log

for f in *nex;
do
r=$(basename "$f" .nex);
grep 'ERROR:' $r/* >> ERRORS.log
grep 'WARNING:' $r/* >> WARNING.log
done




output=$WDIR'checkIQ.log'

rm $output


function checkIQ {
    constraint=$1
    # mistake - prefix=${constraint%.*}
    outfile1=${constraint}.treefile
    outfile2=${constraint}.iqtree
    #echo $outfile1" and "$outfile2" TEST"
    # check if both output files exists, they should only be written at end of run i think
    if [[ -f $outfile1 && -f $outfile2 ]]
    then
        echo $outfile1 >> $output
    fi
}

for f in *nex; 
do 
r=$(basename "$f" .nex); 
cd $r
constraint=${r}.scleroglossa.constraint
checkIQ $constraint

constraint=${r}.toxicoferaP.constraint
checkIQ $constraint
#echo $constraint

constraint=${r}.toxicoferaAI.constraint
checkIQ $constraint
#echo $constraint

constraint=${r}.toxicoferaSA.constraint
checkIQ $constraint
#echo $constraint

constraint=${r}.toxicoferaSI.constraint
checkIQ $constraint
cd $WDIR
done


ls *nex | wc -l 
grep -c '.scleroglossa.constraint.treefile' $output# 
grep -c '.toxicoferaP.constraint.treefile' $output
grep -c '.toxicoferaAI.constraint.treefile' $output
grep -c '.toxicoferaSA.constraint.treefile' $output
grep -c '.toxicoferaSI.constraint.treefile' $output
 
