#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:10:00
#PBS -N log_check_SC
#PBS -o $PBS_JOBNAME.out
#PBS -e $PBS_JOBNAME.err
#PBS -A hpc_jembrown01

runName="SC"
constraint="scleroglossa.constraint"
input=input_${runName}.txt
donelist=donelist_${runName}.txt

WDIR=$PBS_O_WORKDIR
cd $WDIR

rm $input
rm $donelist

for f in *.nex
do
r=$(basename "$f" .ntg.nex)
prefix=${r}.${constraint%%.*}
outfile1=$r/${prefix}.treefile
outfile2=$r/${prefix}.iqtree
echo $outfile1
echo $outfile2
# if output file doesnt exist, write to outfile
if [[ -f $outfile1 && -f $outfile2 ]]
then
    echo ${WDIR}/${r}/ >> $donelist
else
    echo ${WDIR}/${r}/ >> $input
fi
done