#!/bin/bash
#PBS -q workq
#PBS -l nodes=6:ppn=16
#PBS -l walltime=72:00:00
#PBS -N log_gnu_SI
#PBS -o $PBS_JOBNAME.out
#PBS -e $PBS_JOBNAME.err
#PBS -A hpc_jembrown01

runName="SI"
constraint='toxicoferaSI.constraint'
input=input_${runName}.txt
donelist=donelist_${runName}.txt

WDIR=$PBS_O_WORKDIR
cd $WDIR
rm $input
rm $donelist

JOBS_PER_NODE=8
TASK="$WDIR/gnu_task_iq_pbs"$runName".sh"
FILES="$WDIR/$input"


for f in *.nex
do
r=$(basename "$f" .ntg.nex)
prefix=${r}.${constraint%%.*}
outfile1=$r/${prefix}.treefile
outfile2=$r/${prefix}.iqtree
#echo $outfile1
#echo $outfile2
# if output file doesnt exist, write to outfile
if [[ -f $outfile1 && -f $outfile2 ]]
then
    echo ${WDIR}/${r}/ >> $donelist
else
    echo ${WDIR}/${r}/ >> $input
fi
done

# Set up parallel call
# set log file, pass workers, whatever nodefile is, and working directory
PARALLEL="parallel -j $JOBS_PER_NODE --slf $PBS_NODEFILE --wd $WDIR"

# Now call parallel and pass files and task. 
$PARALLEL -a $FILES sh $TASK {} 
