#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=1
#PBS -l walltime=10:00:00
#PBS -N addckp
#PBS -o $PBS_JOBNAME.out
#PBS -e $PBS_JOBNAME.err
#PBS -A hpc_phyleaux11


WDIR=$PBS_O_WORKDIR
cd $WDIR

while read x;
do

# Move to locus folder 
cd $x

# Iterate through all bayes blocks 
for b in *bb
do

# Add append command into mcmc call. 
sed -i.old 's/mcmcp ngen=2000000/mcmcp append=yes ngen=2000000/g' $b

done
cd $WDIR
done < gene.list