#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=1
#PBS -l walltime=10:00:00
#PBS -N grabML
#PBS -o $PBS_JOBNAME.out
#PBS -e $PBS_JOBNAME.err
#PBS -A hpc_phyleaux11


WDIR=$PBS_O_WORKDIR
cd $WDIR

chmod 777 GrabMargLike.sh
rm folder.list
ls -d -- */ &> folder.list
./GrabMargLike.sh 'MargLikeSummary.txt' 'folder.list'

#If a cell is empty, use this to replace with NA. It's super hacky, dont come at me 
sed -e $'s/\t\t/\tNA\t/g' MargLikeSummary.txt| sed -e $'s/\t\t/\tNA\t/g' > MargLikeSummaryNA.txt