Begin MrBayes;
    log start filename=tacocat.toxpoly.log replace;
    execute tacocat.nex;
    constraint Amphisbaenia hard = rhineura_sp bipes_sp;
    constraint Anguimorpha hard = anniella_pulchra heloderma_suspectum varanus_exanthematicus xenosaurus_platyceps lanthanotus_borneensis;
    constraint Dibamidae hard = anelytropsis_sp dibamus_sp;
    constraint Gekkota hard = saltorius_sp strophurus_sp coleonyx_variegatus gekko_sp lialis_sp gonatodes_sp;
    constraint TeiidaeGymno hard = pholidobollus_sp aspidoscelis_tigris tupinambus_sp;
    constraint Iguania hard = hydrosaurus_sp anolis_carolinensis_2 uta_stansburiana;
    constraint Scincoidea hard = cordylus_sp cordylosaurus_sp acontias_sp plestiodon_fasciatus tiliqua_sp cricosaura_sp lepidophyma_sp;
    constraint Outgroup hard = alligator_mississippiensis chrysemys_picta gallus_gallus homo_sapiens sphenodon_sp;
    constraint Snake hard = micrurus_fulvius python_molurus_2 typhlops_jamaicensis;
    constraint Sclero hard = rhineura_sp bipes_sp anniella_pulchra heloderma_suspectum varanus_exanthematicus xenosaurus_platyceps lanthanotus_borneensis anelytropsis_sp dibamus_sp saltorius_sp strophurus_sp coleonyx_variegatus gekko_sp lialis_sp gonatodes_sp pholidobollus_sp lacerta_sp cordylus_sp cordylosaurus_sp acontias_sp plestiodon_fasciatus tiliqua_sp cricosaura_sp lepidophyma_sp aspidoscelis_tigris tupinambus_sp micrurus_fulvius python_molurus_2 typhlops_jamaicensis;
    constraint ToxPoly hard = anniella_pulchra heloderma_suspectum varanus_exanthematicus xenosaurus_platyceps lanthanotus_borneensis hydrosaurus_sp anolis_carolinensis_2 uta_stansburiana micrurus_fulvius python_molurus_2 typhlops_jamaicensis;
    constraint ToxAI hard = anniella_pulchra heloderma_suspectum varanus_exanthematicus xenosaurus_platyceps lanthanotus_borneensis hydrosaurus_sp anolis_carolinensis_2 uta_stansburiana;
    constraint ToxSA hard = anniella_pulchra heloderma_suspectum varanus_exanthematicus xenosaurus_platyceps lanthanotus_borneensis micrurus_fulvius python_molurus_2 typhlops_jamaicensis;
    constraint ToxSI hard = hydrosaurus_sp anolis_carolinensis_2 uta_stansburiana micrurus_fulvius python_molurus_2 typhlops_jamaicensis;
    prset topologypr = constraints (ToxPoly,Amphisbaenia,Anguimorpha,Dibamidae,Gekkota,TeiidaeGymno,Iguania,Scincoidea,Outgroup,Snake);
    prset statefreqpr=dirichlet(1,1,1,1);
    mcmcp ngen=2000000 nruns=2 nchains=4 filename=tacocat.toxpoly;
    ss nsteps=50 burninSS=-4;
    log stop;
End;
